---
ID: "811f2584-dc06-41e0-aca9-46fb0d96c4f6"
Parent: "e0d15a08-a5ff-4c8c-ad3a-b52bcc319c84"
Template: "e0d15a08-a5ff-4c8c-ad3a-b52bcc319c84"
Path: /sitecore/templates/Project/ToolStockSc/Forms/Register/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190716T121056Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
