---
ID: "a9ec58c5-1121-40f9-ab4f-02222a0fd974"
Parent: "ab839eae-3b1d-40a0-821f-d89e0713ce4a"
Template: "ab839eae-3b1d-40a0-821f-d89e0713ce4a"
Path: /sitecore/templates/Foundation/ToolStockSc/Errors/Error/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/windows_close.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190807T124047Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
