---
ID: "804687df-a7a4-4e08-886e-81eb92ddf70a"
Parent: "b01b5c22-7cde-492d-a208-d0151556759c"
Template: "b01b5c22-7cde-492d-a208-d0151556759c"
Path: /sitecore/templates/Project/ToolStockSc/Forms/Actions/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190815T103548Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
