---
ID: "e395d69f-69a8-42f5-a86d-c7b8fd8ed69e"
Parent: "ee453943-32ee-4f2e-9a67-994a9845e7c6"
Template: "ee453943-32ee-4f2e-9a67-994a9845e7c6"
Path: /sitecore/templates/Project/ToolStockSc/Forms/Log In/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190716T083234Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
