---
ID: "e2be0786-c5c4-4a5d-b893-ecdd3567ee08"
Parent: "d823338a-f6bc-46b4-b32b-73ba7a02439a"
Template: "d823338a-f6bc-46b4-b32b-73ba7a02439a"
Path: /sitecore/templates/Project/ToolStockSc/Models/User Reference/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190801T080333Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
