---
ID: "c1ec9d70-aa2e-42c8-a37c-a470b008ec48"
Parent: "5dd41240-fd93-4b4c-8d1f-daff51ed9007"
Template: "5dd41240-fd93-4b4c-8d1f-daff51ed9007"
Path: /sitecore/templates/Feature/Components/Button/Button Option List/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190710T070313Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
