---
ID: "609335c1-868c-4767-878c-9523887306fa"
Parent: "fdd79b9d-4a7f-4412-8b0a-a345b1e7d7d2"
Template: "fdd79b9d-4a7f-4412-8b0a-a345b1e7d7d2"
Path: /sitecore/templates/Project/ToolStockSc/Models/Tool Type/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190730T101625Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
