---
ID: "a1d719fc-b41a-489f-bc56-14cd602803fd"
Parent: "030b92f9-d027-474d-9d62-932efeac27c5"
Template: "030b92f9-d027-474d-9d62-932efeac27c5"
Path: /sitecore/templates/Project/Demo/Demo/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190903T133036Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
