---
ID: "eff3e482-b102-44fb-b9e8-43ea7e57c907"
Parent: "1fc37376-11b6-4254-a7fc-57ca40cde3f0"
Template: "24e7c6f0-333b-4ff3-afdf-e49d8e898340"
Path: /sitecore/content/Sam/ToolStockSc/Home/Keeper/Page Content/Header/Links/Settings
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190730T113250Z
    - ID: "3e6ea968-d969-4296-893f-5b5b301f7e58"
      Hint: Link
      Value: |
        <link text="Settings" anchor="" linktype="internal" class="" title=""  querystring="" id="{CC084338-4337-4E2C-8F97-971A7361733E}" />
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: ru
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190730T113514Z
    - ID: "3e6ea968-d969-4296-893f-5b5b301f7e58"
      Hint: Link
      Value: |
        <link text="Настройки" anchor="" linktype="internal" class="" title=""  querystring="" id="{CC084338-4337-4E2C-8F97-971A7361733E}" />
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
