---
ID: "e2b4d888-a799-4aa1-a267-1721908650a2"
Parent: "4415f053-d7a7-4d94-9bd0-39ab492dcdbb"
Template: "4415f053-d7a7-4d94-9bd0-39ab492dcdbb"
Path: /sitecore/templates/Project/ToolStockSc/Header/Nav Link Rendering Parameter/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190723T105116Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
