---
ID: "494a60fa-258d-46ff-b4be-b7979ce1c68c"
Parent: "57266a47-583f-4876-af06-6e116f4fc069"
Template: "57266a47-583f-4876-af06-6e116f4fc069"
Path: /sitecore/templates/Project/ToolStockSc/Header/Logo link/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190722T111226Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
