---
ID: "6e451b6c-8023-44fc-be15-9db1dcfbe6d4"
Parent: "50011809-a560-4c92-ba18-3b601a6adf7b"
Template: "50011809-a560-4c92-ba18-3b601a6adf7b"
Path: /sitecore/templates/Project/ToolStockSc/Menu/Menu Link Option List/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190722T134839Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
