---
ID: "cba4cb96-730b-4ad0-8100-576c7e05e92e"
Parent: "f735e035-ffcd-46b6-8394-59d465345d69"
Template: "f735e035-ffcd-46b6-8394-59d465345d69"
Path: /sitecore/templates/Feature/Components/Button/Button Rendering Parameter/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190710T070117Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
