---
ID: "de08ab15-7f4d-445e-9c05-9e2c7cea2d9d"
Parent: "0e94475c-a95e-495b-9e77-100709ceeea4"
Template: "0e94475c-a95e-495b-9e77-100709ceeea4"
Path: /sitecore/templates/Project/ToolStockSc/Forms/Tool Creating/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190805T132114Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
