---
ID: "78a5859c-ee3f-472e-86c2-a98dacfd30eb"
Parent: "4f027dc9-d3c7-46bf-9455-13732fc4e216"
Template: "4f027dc9-d3c7-46bf-9455-13732fc4e216"
Path: /sitecore/templates/Project/ToolStockSc/Forms/Change Password/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190726T072233Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
