---
ID: "94361b01-15e5-4f01-b7c7-d55e2e457b66"
Parent: "8b50623f-91cb-46e1-8ad1-db2adebae85d"
Template: "8b50623f-91cb-46e1-8ad1-db2adebae85d"
Path: /sitecore/templates/Project/ToolStockSc/Forms/Profile Editing/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190726T154921Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
