---
ID: "26004c3d-e642-4b45-9a6c-5acd616eb656"
Parent: "fb5fac57-d888-4648-bc26-313286a3bdea"
Template: "24e7c6f0-333b-4ff3-afdf-e49d8e898340"
Path: /sitecore/content/Sam/ToolStockSc/Home/User/Page Content/Header/Links/Settings
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190723T133419Z
    - ID: "3e6ea968-d969-4296-893f-5b5b301f7e58"
      Hint: Link
      Value: |
        <link text="Settings" anchor="" linktype="internal" class="" title=""  querystring="" id="{642A9DC6-9E63-4DE6-A1A8-E358E2A0B1B9}" />
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: ru
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190723T134835Z
    - ID: "3e6ea968-d969-4296-893f-5b5b301f7e58"
      Hint: Link
      Value: |
        <link text="Настройки" anchor="" linktype="internal" class="" title=""  querystring="" id="{642A9DC6-9E63-4DE6-A1A8-E358E2A0B1B9}" />
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
