---
ID: "5e22534a-5370-4744-b83c-2a4ab7527adf"
Parent: "34da2a92-d862-4459-8595-06649c6873ce"
Template: "34da2a92-d862-4459-8595-06649c6873ce"
Path: /sitecore/templates/Project/ToolStockSc/Models/Status/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190801T075151Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
