---
ID: "8f9eafc0-ed7c-4816-9106-dcb65684b306"
Parent: "1c7d7b0c-54a0-4163-acac-6952972327c5"
Template: "1c7d7b0c-54a0-4163-acac-6952972327c5"
Path: /sitecore/templates/Project/ToolStockSc/Header/Nav Link Option List/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190723T104806Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
